// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgCQCp28F53b4N-f7xY7sdFTQ19mdBsk',
    appId: '1:180442008274:web:12d4ab0dd9a8aaf092fb0b',
    messagingSenderId: '180442008274',
    projectId: 'event-planning-app-8ed5a',
    authDomain: 'event-planning-app-8ed5a.firebaseapp.com',
    storageBucket: 'event-planning-app-8ed5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapgbj8OqCFPCrkXPhcToRdwEMtleokFM',
    appId: '1:180442008274:android:38180b8f87c22a9f92fb0b',
    messagingSenderId: '180442008274',
    projectId: 'event-planning-app-8ed5a',
    storageBucket: 'event-planning-app-8ed5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_w7h-JLvg6X3xixnGSqmPElrh8ls0_A',
    appId: '1:180442008274:ios:3607b98b650858f592fb0b',
    messagingSenderId: '180442008274',
    projectId: 'event-planning-app-8ed5a',
    storageBucket: 'event-planning-app-8ed5a.firebasestorage.app',
    iosBundleId: 'com.example.evntPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_w7h-JLvg6X3xixnGSqmPElrh8ls0_A',
    appId: '1:180442008274:ios:3607b98b650858f592fb0b',
    messagingSenderId: '180442008274',
    projectId: 'event-planning-app-8ed5a',
    storageBucket: 'event-planning-app-8ed5a.firebasestorage.app',
    iosBundleId: 'com.example.evntPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxgCQCp28F53b4N-f7xY7sdFTQ19mdBsk',
    appId: '1:180442008274:web:6b61e1819e9c71c392fb0b',
    messagingSenderId: '180442008274',
    projectId: 'event-planning-app-8ed5a',
    authDomain: 'event-planning-app-8ed5a.firebaseapp.com',
    storageBucket: 'event-planning-app-8ed5a.firebasestorage.app',
  );
}
